name: Example Workflow

on:
  workflow_dispatch:

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/checkout@v2 #actions is the github actions library
      - name: Preparation 
        run: |
            echo $ pwd
            pwd
            echo $ ls -la
            ls -la
            pip install pytest
      - name: Check Parser
        run: |
            echo pytest parser.py
            pytest parser.py